### ISSUE TITLE
Should we remove legacy support?

### ISSUE THREAD

**Issue by steelbrain** [AtomLinterPlus/linter-plus#2]
Because we aren't linter anymore, we don't **need** to support the old stuff. So should we remove it's support and push authors to use the new API or keep it in the codebase. What are your opinions?

__Note:__ Those packages have hard-coded `linter` so I am not sure keeping that code would work, because that import would fail for them.

**Comment by k2b6s9j** [comment]
I was also thinking about this. We could move Legacy Linter support into a separate package. That package could relay messages from the original API to the new API, and possibly create a pseudo `linter` package.

**Comment by steelbrain** [comment]
IMHO, we should leave the linter package to deal with them and support the new ones. How does that sound?

**Comment by k2b6s9j** [comment]
Okay. But could we create a basic Linter class so that linters that wish to support both APIs don't have to completely rewrite?

**Comment by k2b6s9j** [comment]
I guess in other words, not try to completely supplement for AtomLinter but, provide some syntactic sugar for developers wishing to support both so that all they have to do is provide a service and load packages dynamically.

**Comment by steelbrain** [comment]
Do you have any structure in mind for that basic class?

**Comment by k2b6s9j** [comment]
A `Linter` class containing variables `@cmd`, `@syntax`, `@linterName`, `@errorStream`, and methods `lintFile: (filePath, callback)`, `constructor: (editor)`, and `createMessage: (match)`

**Comment by k2b6s9j** [comment]
That should cover most use cases with minimal changes.

**Comment by steelbrain** [comment]
I am not sure if we'll be provide a constructor like that, 'cause we share one linter instance across all editor. We could however, pass it in the lintFile method.

**Comment by k2b6s9j** [comment]
Sounds fair.

**Comment by steelbrain** [comment]
You will see it here https://github.com/AtomLinterPlus/atom-linter-base
very soon

**Comment by k2b6s9j** [comment]
Great. That should allow us to keep most of the existing Linter code and make for an easy transition if we all do end up unifying in the Atom core. Which would make the users and the developers lives easier.

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinterPlus/linter-plus/commit/c87f37c881549553b2644b4129236b778c3db1ef
