### ISSUE TITLE
API questions/suggestions

### ISSUE THREAD

**Issue by lierdakil** [AtomLinterPlus/linter-plus#3]
While reading wiki page on service-provider API, I found some decisions a little bit puzzling.

Here's a list of what immediately popped into my mind:

1. Why pass both editor and buffer to `lint`? Buffer is always available through `getBuffer()`, and in most cases editor reference is not needed at all, since plumbing should be handled by AtomLinter anyway.
2. While on topic, why use positional parameters as arguments to `lint`, and not an object? Using object would be considerably more flexible with little overhead, using CoffeeScript's argument object unpacking. Of course, if you choose to use a single `editor` argument, that's not applicable.
3. `scope` and `scopes` seem a little misleading names. Something more descriptive, like `grammarScopes` and `linterScope` would be a bit better.
4. Same goes for Message and Trace fields: `position` is not position, but range, and `file` is not a file, but a URI (presumably), or file path (if you prefer), so `fileURI`/`filePath` might be more descriptive (btw, is it absolute or relative to project directory?). `message` and `html` could be a little more descriptive as well, but I'm not sure I understand semantics correctly, so I can't offer any options on `html`. I'd rename `message` to `text`, though, since whole object itself is semantically a "message".

That's from the top of my head.

**Comment by steelbrain** [comment]
Agreed on point 1
Point 2 isn't gonna be valid since we're only gonna have a single editor argument.
Agreed on point 3.
and `file` is a FilePath yes, and renaming `message` to `text` sounds all good to me.

**Comment by lierdakil** [comment]
I strongly advise to rename `position` to `range`. Reason is, for anyone who works with Atom API, `position` implies a `Point`, which is not the case here.

On the topic of passing editor, is it really necessary? Are there examples where passing editor reference is beneficial, compared to passing just a buffer reference? I can't think of any, but maybe it's just me.

**Comment by steelbrain** [comment]
This is what the trace and position looks like when consumed properly
![Screenshot](https://cloud.githubusercontent.com/assets/4278113/8051890/80620880-0e36-11e5-95de-0ac04cbdf66e.png)

**Comment by lierdakil** [comment]
But... that's a `Range`, isn't it? At least that's what docs say...

**Comment by steelbrain** [comment]
It is. and it'll be renamed. Just like you suggested.

**Comment by k2b6s9j** [comment]
Oh... So that's what a trace is... I was confused about that.

**Comment by lierdakil** [comment]
@steelbrain, then I'm afraid I don't quite understand what your previous comment is related to:

> This is what the trace and position looks like when consumed properly

**Comment by steelbrain** [comment]
@lierdakil It meant that the current state of them produces that output, the output will remain the same but the API parameters will be renamed. Thoughts @k2b6s9j ?

**Comment by lierdakil** [comment]
Oh, okay.

**Comment by k2b6s9j** [comment]
Sounds great. Especially if someone without an AtomLinter bias thinks they look good.

**Comment by k2b6s9j** [comment]
Please continue conversation at AtomLinter/linter-plus#48
