### ISSUE TITLE
selected tab text hard to read

### ISSUE THREAD

**Issue by devoncarew** [AtomLinterPlus/linter-plus#4]
The selected tab text is hard to read:

![screen shot 2015-06-15 at 11 00 57 am](https://cloud.githubusercontent.com/assets/1269969/8166640/f19a6b7a-134d-11e5-8dc8-845695e8ced1.png)

The text-shadow attribute makes the text blurry.

Also, the linter-plus status bar takes up a lot of space on my status line. I think we can present the same info in a more compact format.

**Comment by steelbrain** [comment]
I didn't know we had a text-shadow attribute, Also what variable would you suggest from the list https://github.com/atom/atom-dark-ui/blob/master/styles/ui-variables.less (the values change from theme to theme)

and about the space, What do you propose the max-height to be?

**Comment by devoncarew** [comment]
I think the style is contributed from the status-line parent, but it's interacting badly with the tab text.

For the space, I meant the horizontal space used. It contributes 3 items, with will mostly (hopefully) have no errors.

I'm happy to send a PR with some style changes if you like.

**Comment by steelbrain** [comment]
@devoncarew We would love to have that PR, Please note that the project has moved back to github.com/AtomLinter/linter-plus
and there are quite a few styles.less changes in https://github.com/AtomLinter/linter-plus/pull/54
so You might have to wait until it's merged if you want to avoid conflicts

**Comment by devoncarew** [comment]
Sure, will wait for that to land.

I installed `linter-plus` from the package site - the last published version may reference the old repo?

**Comment by steelbrain** [comment]
Yeah, it references the old repo 'cause the new one hasn't been published yet, We are trying to get it done ASAP to be honest.

**Comment by steelbrain** [comment]
and that PR has been merged in btw.

**Comment by steelbrain** [comment]
Fixed by the recent style changes by simurai
