### ISSUE TITLE
Remove from APM.

### ISSUE THREAD

**Issue by k2b6s9j** [AtomLinterPlus/linter-plus#9]
This should be done once Nuclide documentation updates.

**Comment by steelbrain** [comment]
Yep.

**Comment by k2b6s9j** [comment]
Give me a sec, I'm fixing it.

**Comment by k2b6s9j** [comment]
So once Nuclide updates all references for linter, I'll publish.

**Comment by steelbrain** [comment]
Sounds good to me

**Comment by steelbrain** [comment]
Done.
